name: Scheme
on:
  pull_request:
    paths:
      - "**/*.gen.yaml"

jobs:
  securityScheme:
    runs-on: ubuntu-latest
    name: Add security schemes
    steps:
      - name: git-checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"

      - name: Update openapi docs
        run: |
          # Read the changed files from the previous step
          go mod init github.com/0xsequence/docs 
          go get github.com/mikefarah/yq/v4@latest 
          go run github.com/mikefarah/yq/v4 -e -i '.security=[{"ApiKeyAuth":[]}]' docs/pages/api/marketplace/marketplace.gen.yaml
          go run github.com/mikefarah/yq/v4 -e -i '.security=[{"ApiKeyAuth":[]}, {"BearerAuth":[]}]' docs/pages/api/metadata/metadata.gen.yaml
          go run github.com/mikefarah/yq/v4 -e -i '.security=[{"ApiKeyAuth":[]}]' docs/pages/api/indexer/indexer.gen.yaml
          go run github.com/mikefarah/yq/v4 -e -i '.security=[{"ApiKeyAuth":[]}]' docs/pages/api/relayer/relayer.gen.yaml

      - name: Push changes
        uses: 0xsequence/actions/git-commit@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN_GIT_COMMIT }}
        with:
          files: "docs/pages/api/**/*.gen.yaml"
          branch: ${{ github.head_ref }}
          ## since openapi docs are generated and PR is automatically created there is no need to try create new one
          pr_title: "[AUTOMATED] Add global security schemes"
          pr_create: false
