name: Build search-index on weekly cadence

on:
  schedule:
  - cron: "0 8 * * 1"

jobs:
  build:
   runs-on: ubuntu-latest
   name: Build and Push
   steps:
    - name: git-checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    
    - name: Install dependencies
      run: |
        npm install -g pnpm@8.15.4
        pnpm install
    
    - name: Build
      run: pnpm run search-build
      
    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        GIT_CLONE_PROTECTION_ACTIVE: false
        BRANCH: build
        FOLDER: ./docs/dist/.vocs
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: "Build: ({sha}) {msg}"
